# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ruitaopan"


[[social]]
identifier = "email"
name = "Email"
url = "mailto:ruitaopan05@foxmail.com"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"